# Generated by Django 4.2.5 on 2023-09-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='сalories_in_uom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Калорийность в ЕИ'),
            preserve_default=False,
        ),
    ]
