# Generated by Django 4.2.5 on 2023-09-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_ingredient_сalories_in_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Выручка за месяц',
                'verbose_name_plural': 'Выручка',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='chosen_ingrs',
            field=models.ManyToManyField(blank=True, related_name='chosen_ingrs', to='bot.ingredient', verbose_name='Обязательно наличие ингредиентов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='bot.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='excluded_ingrs',
            field=models.ManyToManyField(blank=True, related_name='excluded_ingrs', to='bot.ingredient', verbose_name='Исключить ингредиенты'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_сalories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум калорий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='min_сalories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимум калорий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='type_of_meal',
            field=models.ManyToManyField(blank=True, to='bot.mealtype', verbose_name='Запрещенные типы блюд'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
    ]
