# Generated by Django 4.2.5 on 2023-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_revenue_remove_client_settings_settings_chosen_ingrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='День оплаты'),
        ),
        migrations.AddField(
            model_name='client',
            name='renew_sub',
            field=models.BooleanField(default=False, verbose_name='Продление подписки'),
        ),
    ]
