# Generated by Django 4.2.5 on 2023-09-29 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_client_payment_date_client_renew_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='max_сalories',
            field=models.IntegerField(default=0, verbose_name='Максимум калорий'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='month',
            field=models.DateField(default=datetime.date(2023, 9, 1), verbose_name='Месяц'),
        ),
    ]
