# Generated by Django 4.2.5 on 2023-09-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_revenue_max_сalories_revenue_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='max_сalories',
        ),
        migrations.AddField(
            model_name='revenue',
            name='revenue_sum',
            field=models.IntegerField(default=0, verbose_name='Выручки за месяц'),
        ),
    ]
