# Generated by Django 4.2.5 on 2023-10-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='month',
            field=models.DateField(default=datetime.date(2023, 10, 1), verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue_sum',
            field=models.IntegerField(default=0, verbose_name='Выручка за месяц'),
        ),
    ]
